### ISSUE TITLE
Effects won't load for The Witcher 3 in Reshade 4.9.1

### ISSUE THREAD

**Issue by Nickpal1** [TreyM/MShaders#3]
Hey this is fantastic but in the readme can you include instructions where to put the files? Usually I don't have any issues adding new effects to Reshade but for some reason with Reshade 4.9.1, the Atmospheric Density.fx file won't load in The Witcher 3 (it's marked as failed to load along with VHSM.fx.). Thanks.

**Comment by TreyM** [comment]
You should maintain the folder structure shown here. Place the contents of both the Shaders and Textures folders inside the folders of the same name in the reshade-shaders folder that is installed with ReShade. Then you'll need to manually add the effects search path to the MShaders folder in ReShade's settings tab.

These issues should go away when crosire adds this repo to the ReShade installer.

**Comment by Nickpal1** [comment]
Thanks for the reply. I did exactly that, placed the Shader and Texture folders in their respective Reshade folders and added the effects and texture path manually in the Reshade settings tab but still no joy..no worries I'll wait for crosire to add them to the repo.

**Comment by Nickpal1** [comment]
I got it to work, finally. It looks great, thanks!
